//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDocGia()
        {
            this.tblMuons = new HashSet<tblMuon>();
        }
    
        public string MADG { get; set; }
        public string HOTEN { get; set; }
        public string NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string LOP { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
        public string GHICHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMuon> tblMuons { get; set; }
    }
}
