//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMuon
    {
        public string MADG { get; set; }
        public string MASACH { get; set; }
        public string SOPHIEUMUON { get; set; }
        public System.DateTime NGAYMUON { get; set; }
        public System.DateTime NGAYTRA { get; set; }
        public string XACNHANTRA { get; set; }
        public string GHICHU { get; set; }
    
        public virtual tblDocGia tblDocGia { get; set; }
        public virtual tblSach tblSach { get; set; }
    }
}
