//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanVien
    {
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string QUYENHAN { get; set; }
        public string TENNV { get; set; }
        public string DiaChi { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string ChucVu { get; set; }
        public string Tuoi { get; set; }
    }
}
