//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSach()
        {
            this.tblMuons = new HashSet<tblMuon>();
        }
    
        public string MASACH { get; set; }
        public string TENSACH { get; set; }
        public string MATG { get; set; }
        public string MANXB { get; set; }
        public string MaLv { get; set; }
        public string NAMXB { get; set; }
        public Nullable<int> SOTRANG { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string NGAYNHAP { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> SOSACHHONG { get; set; }
    
        public virtual tblLinhVuc tblLinhVuc { get; set; }
        public virtual tblNXB tblNXB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMuon> tblMuons { get; set; }
        public virtual tblTacGia tblTacGia { get; set; }
    }
}
